id: Content Updates
inputs: []
name: Content Updates
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 763d60ba-64d3-48fe-8381-0c0673caecb1
      iscommand: false
      name: ""
      version: -1
    taskid: 763d60ba-64d3-48fe-8381-0c0673caecb1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      bucket_name:
        simple: shula
      object_name:
        simple: content/packs/index.zip
      saved_file_name: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves object data into a file.
      id: 4dbab157-b077-442d-8343-83206dfe2f14
      iscommand: true
      name: Download Index.zip from marketplace-dist
      script: '|||gcs-download-file'
      type: regular
      version: -1
    taskid: 4dbab157-b077-442d-8343-83206dfe2f14
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      entry_id:
        simple: ${File.EntryID}
      last_message_time_str:
        simple: "2021-03-26T17:33:28Z"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35bc6558-aff8-4c93-84ea-2f7a74168928
      iscommand: false
      name: Get New Released Packs
      script: 5edebc56-3051-49c0-880c-c08c99804d7d
      type: regular
      version: -1
    taskid: 35bc6558-aff8-4c93-84ea-2f7a74168928
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
